### ISSUE TITLE
import fairing hangs in notebook

### ISSUE THREAD

**Issue by hamedhsn** [kubeflow/fairing#119]
when I import fairing it hangs. digging a bit and found that the current dir is `/home/jovyan`
and then preprocessor class scan all the files under that path`input_files=glob.glob("**", recursive=True)` 
https://github.com/kubeflow/fairing/blob/master/fairing/preprocessors/base.py#L24
and if like my case, I have a TB of data under that it takes ages to scan them all.

I think the implementation needs to pass the right path in a better way.

**Comment by r2d4** [comment]
Thats a good observation. Maybe we don't use glob pattern by default. Or only glob python files. 

Any training data or configuration that needs to be added to the container should use the explicit `output_map`

**Comment by karthikv2k** [comment]
Thanks @hamedhsn . I was about to create this issue :)
In my case, I imported fairing and it scanned all the files in pwd and then I removed some files as part of my code and then when I tried running a remote job, it failed because of the missing file(s). 

Will fix it as part of the PR that I am working on.

**Comment by hamedhsn** [comment]
thanks guys :)
the other thing I noticed in here https://github.com/kubeflow/fairing/blob/master/fairing/preprocessors/base.py#L43
if you have more python files it does pick the first file which might not be the right one.
