### ISSUE TITLE
Figure out python packaging for fairing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#234]
I think fairing is imported as 

```
import fairing
```

Should we instead make this a subpackage in "kubeflow"

e.g.

```
import kubeflow.fairing
```

**Comment by jlewi** [comment]
@karthikv2k What is the plan for 0.6 ? Do you think we can/should change the import as part of 0.6?

**Comment by jlewi** [comment]
@karthikv2k is thinking we will stick with `import fairing` for 0.6 because there are a lot of places that need to be updated.

**Comment by jinchihe** [comment]
@jlewi Agree with you, as logged https://github.com/kubeflow/kubeflow/issues/3683, we should have a unified `kubeflow` SDK, so sub-project will import as `import kubeflow.fairing` , `import kubeflow.kfp` and `import kubeflow.lfmd` etc ...

**Comment by jlewi** [comment]
So should we change to kubeflow.fairing in 0.6?

**Comment by swiftdiaries** [comment]
Yeah, +1

**Comment by jinchihe** [comment]
@jlewi Guess you want to @ me? :-) I will take this.
/assign @jinchihe

**Comment by jinchihe** [comment]
hello @jlewi @animeshsingh 

After thinking, there are two proposals:

## Option 1:  Radical way
1. Rename the project name to `kubeflow-sdk` or `kubeflowsdk` (or better name?).
2. The pacakage name will be `kubeflow` (in Pypi), user will install by `pip install kubeflow`
3. Make new folder named `kubeflow`. And move all current `fairing` files to the create `kubeflow` as subpackage, we also can sync regularly from other components later to kubeflow (such as `kubeflow.kfp` and `kubeflow.lfmd`, `kubeflow.kfserving`)
4. Update the `setup.py` files and other python file (imports to relative import way). 
5. Update the samples to import fairing as `from kubeflow import fairing`, includes other repo such as `kubeflow examples`.

**Pros** Radical way, we can build unified kubeflow sdk package.
**Cons**: Changes are big.

## Option 2: Conservative way
1. Just update required file from fairing to `kubelow.fairing` such as in setup.py and __init__ files, and import statements.
2. Update all samples by `import kubeflow.fairing...` and other repos.

**Pros**: changes is small.
**Cons**: seems so hack this way.

Personally I prefer to option 1, since the option 2 is so hack and Option 1 can let us build unified sdk package, user no need to install python package for each components that may let user confusing or unhappy.

Could you please let me know your viewpoints? Thanks a lot!
 
/cc @karthikv2k @abhi-g @gyliu513

**Comment by abhi-g** [comment]
I prefer the conservative way for now as we want to focus all resources on
1.0. given the amount of work involved in all of the major application
components.

Note that my suggestion is purely based on time and resource constraints
and not based on technical merit.

**Comment by jinchihe** [comment]
Hello @abhi-g, Great thanks for your comments!

Discussed someones such as @gyliu513 and @hougangliu, we fully understand your concern about time and resource constraints, after careful consideration, we still suggest taking option 1 , there is a successful case in [openstack](https://github.com/openstack/openstacksdk), we can do a similar SDK. The option 2 is useless in fact.

For you concern, I can take more time to maintain Kubeflow Fairing, and if needed, I can introduce more resource from IBM to contribution this, to ensure we can finish that before 0.7.

I tried to created the PR #359 to do that , seems the effort is not as big as we thought :-) For the change, the earlier the better.

**Comment by jlewi** [comment]
Do we need to need create a single unified repository in order to get to the world where users can do

```
from kubeflow import kfp
from kubeflow import fairing
from kubeflow import kfserving 
etc....
```

Can we use [namespace packaging](https://packaging.python.org/guides/packaging-namespace-packageshttps://packaging.python.org/guides/packaging-namespace-packages/) to allow every project/repo/working group etc.. to define its own subpackages within the kubeflow python namespace?

So if every project follows option 2 then users would be able to do 

```
pip install <{PKG1-name} | {GITHUB link}>
```
* Where the pkg name is determined by how we publish to PyPi

If we want to create a unified pypi package to install all sub-packages; can we do that at release time? e.g. combine the subpackages from all the repos and then build and upload a single pip package?

If we create a single uber SDK repo and package, how do we scale that as the number of sub-packages grows? How do we mediate disagrements about what should be included in the SDK and what not?

The general approach in Kubeflow is to try to avoid that by emphasizing modularity and composability.

I think this is a major advantage of Option 2; users can decide which subpackages to install and at what versions.

**Comment by jinchihe** [comment]
@jlewi Really thanks for the great discussion. I got your concerns. I'm changing my mind...

> If we want to create a unified pypi package to install all sub-packages; can we do that at release time? e.g. combine the subpackages from all the repos and then build and upload a single pip package?

I think that's not a problem for the resource to finish that, if cannot I can introduce more resource from IBM to finish that.

> If we create a single uber SDK repo and package, how do we scale that as the number of sub-packages grows?

I think we can add new sub directory for new repo.

> How do we mediate disagrements about what should be included in the SDK and what not?

Personally I think this is big challenge, in fact I'm worried about that too. Same repos owner may have different viewpoint for this since that's easy to maintain if sdk and core in same repo.

Yes, the namespace pacakging may be better way for us. if so, I perfer use the [Native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages) which added from Python 3.3, Python 2 may not be support but I think that's OK since Python 2 will not be maintained soon.

I am now more inclined to namespace packaging. will update PR later. Thank you again!

**Comment by jlewi** [comment]
How much more work is using using namespace packaging then Native namespace packaging?

I think its potentially reasonable to say that our python client library or specific python client libraries e.g. fairing might be only Python 3. But that seems like a decision that might be worth some broader discussion. So perhaps we should just use namespace packages to avoid blocking progress on SDK refactoring until we are ready to commit to Python 3.

I believe some of our python "packages" are already using namespace packaging
https://github.com/kubeflow/testing/blob/master/py/kubeflow/__init__.py

**Comment by jinchihe** [comment]
The effort should be small. Yes, if we want to also support Python 2, we can use [pkgutil-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages) as the `kubeflow/testing` used. 

Will update that PR tomorrow. Thanks.

**Comment by gyliu513** [comment]
@jlewi @jinchihe I prefer that we take Python 2 as low priority, as Python 2 will come to an end in 2020, people may already start the migration process.

Please checkout https://www.codetd.com/en/article/7108696 and https://gestaltit.com/favorites/rich/saying-goodbye-to-python-2-7/ for detail.

**Comment by jlewi** [comment]
@gyliu513 I don't think we need to take on extra work to support python2; but I think we want to make 1 change at a time.

The kubeflow python packages are currently using namespace packaging. So if we switch to native namespace packaging then we have to make changes across all our repositories. That could slow down doing the package renaming. I think getting the package renaming done sooner is more important because that is user facing.

So my vote is to get the package renaming done first and then after that do things like remove py2 support/features.

**Comment by jinchihe** [comment]
Already updated the PR, used [pkgutil-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages) which supports Python 2.
