### ISSUE TITLE
Using Docker hub as Docker Registry

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/fairing#248]
I try to use my docker repository from here: https://hub.docker.com/ as `DOCKER_REGISTRY` in this notebook:  https://github.com/kubeflow/fairing/blob/master/examples/notebook/hello-world.ipynb.
Do we have some documentation how I can do it, if I don't want to use GCP for Docker repositories?
 
/cc @karthikv2k

**Comment by karthikv2k** [comment]
Yes, you can use docker hub. You need to run "docker login"  to get the right creds to push.

If you are using KF notebooks then you need to run "docker login" within the container or copy your docker config (~/.docker/config.json) from your laptop to the notebook instance.

You may need to install docker client in the container to run "docker login" in the notebook instance.

CC @joeliedtke 
Joe, this issue needs some documentation.

**Comment by joeliedtke** [comment]
Thanks, I've added this as a note on kubeflow\website 594

**Comment by joeliedtke** [comment]
Documentation for how to configure Fairing has been added at: 
https://www.kubeflow.org/docs/fairing/configure-fairing/

**Comment by andreyvelich** [comment]
Thanks. I can close it.

**Comment by benoitdr** [comment]
@karthikv2k , 
> If you are using KF notebooks then you need to run "docker login" within the container or copy your docker config (~/.docker/config.json) from your laptop to the notebook instance.

This is not working on a fresh kubeflow 0.6.2 local cluster. It would require sudo privilege for the jovyan user in the conainter and this is not granted on the default image (gcr.io/kubeflow-images-public/tensorflow-1.13.1-notebook-cpu:v0.5.0)

creating/editing .docker/config.json is not possible since the .docker directory belongs to root 
drwx------ 2 root   root  4096 Apr  6 07:15 .docker

Any clue how to work it around ?

Don't now if this issue can be reopened or if it is better to create a new one

**Comment by xauthulei** [comment]
@benoitdr, I also met this issue, in my work rounds, I build the tensorflow notebook images based on the [Dockerfile](https://github.com/kubeflow/kubeflow/blob/master/components/tensorflow-notebook-image/Dockerfile), then  create a new Jupyter using  our self built `Custom Image` with  docker installed or configured. Thanks

**Comment by pvgbabu** [comment]
@xauthulei Is your Docker file works for on-prem kubeflow.
