### ISSUE TITLE
Use absolute python imports

### ISSUE THREAD

**Issue by jlewi** [kubeflow/fairing#383]
/kind feature

It looks like some of the code is using relative imports; e.g.
https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/builders/cluster/cluster.py#L6

We should probably clean that up and use absolute imports everywhere. In my experience using relative imports is brittle.

**Comment by nrchakradhar** [comment]
I will give it a try this week.

**Comment by jinchihe** [comment]
Hi @jlewi @nrchakradhar some relative imports are introduced while renaming kubeflow.fairing, since I think the absolute imports would make the statement too long such as:

 `from kubeflow.fairing.builders.cluster.context_source import ContextSourceInterface`

And one clear advantage of relative imports is that they are quite succinct. Depending on the current location, they can turn the ridiculously long import statement, for example:

`from .cluster.context_source import ContextSourceInterface`.

Since there are all under kubeflow/fairing DIR, should have no conficts import. Or just enhance such as `from ... import`?  comments?

**Comment by nrchakradhar** [comment]
@jinchihe My understanding is that there is no clear technical winner for relative or absolute imports, its a matter of choice. Usage of few classes like "Job", "KubernetesManager" were a bit confusing to start with but is not that big a concern though.

**Comment by jlewi** [comment]
I've been burned by relative imports in the past.

PEP style guide recommends absolute imports
https://www.python.org/dev/peps/pep-0008/

Stylistically I also favor importing an entire module and not individual classes

**Comment by jinchihe** [comment]
@jlewi OK, so let's follow PEP style. Thanks.
