### ISSUE TITLE
Make new high level API using KFServing

### ISSUE THREAD

**Issue by jinchihe** [kubeflow/fairing#428]
/kind feature

**Describe the solution you'd like**
Make the high level API for deploy service using kfserving. For now, there are two high Level APIs,`TrainJob` and `PredictionEndpoint` , the `PredictionEndpoint`  is using deployer `Serving`. I think we should create new high level API which calls deployer `KFServing`. That's easy for deploy inference service.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by xauthulei** [comment]
@jinchihe , I will working on this, Thanks

**Comment by jinchihe** [comment]
@xauthulei Exciting! Thanks!

**Comment by jlewi** [comment]
Should we get rid of the high level APIs rather than continue to expand them? 

fairing has "ml_tasks"
https://github.com/kubeflow/fairing/tree/master/kubeflow/fairing/ml_tasks

Which combine together the lower level APIS (preprocessors, builders, deployers).

In a lot of our examples, we find that this API is too constraining and its easier just to use the low level APIs directly.

Should we deprecate "ml_tasks" (e.g. PredictionEndpoint) rather than continuing to extend and expand it?

**Comment by jinchihe** [comment]
@jlewi Thanks for the comments.

Let talk about `ml_tasks` in #476 

/close
